---
title: "week05_001-live"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE)
library(tidyverse)
```

# Monday

datasets

```{r}
drinks = tibble(
  Row = 1:4,
  Drink = c("Milk Tea", "Espresso", "Latte", "Espresso"),
  Cafe = c("Happy Tea", "Daily Grind", "Daily Grind", "Bev's Beverages"),
  Price = c(4, 2, 3, 2)
)

drinks
```

```{r}
discounts = tibble(
  Row = 1:3,
  Coupon = c("25%", "50%", "5%"),
  Cafe = c("Happy Tea", "Daily Grind", "The Roast")
)

discounts
```

## Mutating join

- `left_join`

```{r}
left_join(drinks, discounts, by = join_by("Cafe")) # lose information abiut the 2nd dataset and the rows that didn't have information in the second dataset will have NAs in it.
```

```{r}
left_join(drinks, discounts)
```

```{r}
right_join(drinks, discounts, by = join_by("Cafe"))
```


- `full_join`

```{r}
drinks %>% full_join(discounts, by = join_by("Cafe"))

bind_rows(drinks, discounts)
```

```{r}
drinks %>% inner_join(discounts, by = join_by("Cafe"))
```

```{r}
discounts1 <- discounts %>% rename(Locations = Cafe)%>% select(-Row)

discounts1 
```

```{r}
drinks %>% left_join(discounts1, by = join_by(Cafe == Locations))

drinks %>% left_join(discounts1, by = Cafe == Locations) # the common column names have to be inside the join_by function

drinks %>% left_join(discounts, by = "Row")
```

## Filtering join

```{r}
drinks %>% semi_join(discounts, by = "Cafe") # it only filters out rows of the first dataset that match with the second dataset
```

```{r}
drinks %>% inner_join(discounts, join_by("Cafe"))
```



```{r}
drinks %>% anti_join(discounts, by = "Cafe")
```

```{r}
left_join(drinks, discounts, join_by(Cafe))
right_join(discounts, drinks, join_by(Cafe))
```

# Friday

## Pivoting

```{r}
players = tibble(
  player = c("Erling Haaland", "Kevin De Bruyne"),
  goals = c(36, 7),
  assists = c(8, 16),
  games = c(35, 32)
)

players1 = tibble(
  player = c("Erling Haaland", "Kevin De Bruyne"),
  goals = c(36, 7),
  assists = c(8, 16),
  games = c(35, 32),
  title = c("player_of_the_match", "none")
)

players
```

- `pivot_longer()`

```{r}
pivot_longer(players, c(goals, assists, games))

pivot_longer(players, c(goals, assists, games), names_to = "Statistic", values_to = "Scores")

players1 %>% pivot_longer(-c(player, title))

players %>% pivot_longer()

players_longer <- players %>% pivot_longer(goals:games, names_to = "Statistic", values_to = "Scores")

players_longer
```

- `pivot_wider()`

```{r}
players_longer %>% pivot_wider(names_from = Statistic, values_from = Scores)
```

Example:

```{r}
table1
```

```{r}
table2

# going from table1 to table2

table1 %>% pivot_longer(cases:population, names_to = "type", values_to = "count")
```

```{r}
# going from table2 to table1

table2 %>% pivot_wider(names_from = type, values_from = count)
```

# a look into geom_text

```{r}
mendota <- read_csv("../../data/lake-mendota-winters-2024.csv")
```
```{r}
ggplot(mendota, aes(x = duration))+
  geom_histogram(
    color = "blue",
    fill = "skyblue"
  ) +
  geom_text(x = 80,
            y = 21,
            label = "this is the tallest bar ->")

ggplot(mendota, aes(x = duration, y = year1))+
  geom_point() +
  geom_text(x = 80,
            y = 2000,
            label = "this is the tallest bar ->",
            color = "red")
```

# End of Midterm 1 portion




