---
title: "week05_003-live"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE)
library(tidyverse)
```

# Wednesday

##datasets

```{r}
drinks = tibble(
  Row = 1:4,
  Drink = c("Milk Tea", "Espresso", "Latte", "Espresso"),
  Cafe = c("Happy Tea", "Daily Grind", "Daily Grind", "Bev's Beverages"),
  Price = c(4, 2, 3, 2)
)
drinks
```

```{r}
discounts = tibble(
  Row = 1:3,
  Coupon = c("25%", "50%", "5%"),
  Cafe = c("Happy Tea", "Daily Grind", "The Roast")
)
discounts
```

## mutating joins

- `left_join()`

```{r}
left_join(drinks, discounts, by = "Cafe")
```

```{r}
left_join(drinks, discounts)
```


- `right_join()`

```{r}
right_join(drinks, discounts, by = "Cafe")
```

- `full_join()`

```{r}
full_join(drinks, discounts, by = "Cafe")
full_join(discounts, drinks, by = "Cafe")
```
- `inner_join()`

```{r}
inner_join(drinks, discounts, by = "Cafe")
```

```{r}
discounts1 <- discounts %>% rename(Locations = Cafe) %>% select(-Row)

discounts1
```

```{r}
left_join(drinks, discounts1, by = join_by(Cafe == Locations))
```


## filtering joins

- `semi_join()`

```{r}
drinks %>% semi_join(discounts, by = "Cafe")

drinks %>% inner_join(discounts, by = "Cafe")
```

- `anti_join()`

```{r}
drinks %>% anti_join(discounts, by = join_by(Cafe))

discounts %>% anti_join(drinks, by = join_by(Cafe))
```
## Exercise

```{r}
band_instruments
```
```{r}
band_members
```

```{r}
inner_join(band_instruments, band_members)
```

## Pivoting

```{r}
players = tibble(
  player = c("Erling Hoaland", "Kevin De Bruyne"),
  goals = c(36, 7),
  assists = c(8, 16),
  games = c(35, 32)
)

players1 <- players %>% mutate(title = c("player_of_match", "none"), wins = c(T, F))

players1 
```

- `pivot_longer()`

```{r}
players %>% pivot_longer(c(goals, assists, games))

players_long <- pivot_longer(players, goals:games, names_to = "Statistic", values_to = "Score")

players %>% pivot_longer(-player)
```

```{r}
players1 %>% pivot_longer(-c(player, title))
```

- `pivot_wider()`

```{r}
players_long <- pivot_longer(players, goals:games, names_to = "Statistic", values_to = "Score")

players_long %>% pivot_wider(names_from = Statistic, values_from = Score)

pivot_longer(players, goals:games) %>% pivot_wider()
```


Exercise:

```{r}
table1
```

```{r}
table2
```


> What type of dataset is Table1 compared to table2

Table1 is the wider dataset and Table2 is the longer dataset



```{r}
# table1 -> table2

table1 %>% pivot_longer(c(cases, population), names_to = "type", values_to = "count")

table1 %>% pivot_longer(-c(country, year), names_to = "type", values_to = "count")

# this would work as well but the output is not table2

table1 %>% pivot_longer(c(year, cases, population), names_to = "type", values_to = "count")
```

```{r}
# table2 -> table1

table2 %>% pivot_wider(names_from = type, values_from = count)
```


```{r}
mendota <- read_csv("../../data/lake-mendota-winters-2024.csv")
```

```{r}
ggplot(mendota, aes(duration)) +
  geom_histogram(
    color = "skyblue",
    fill = "blue"
  ) +
  geom_text(
    x = 79,
    y = 21,
    label = "this is the tallest bar ->",
    color = "red"
  )
```


# End of Midterm 1 portion







