---
title: "week05_004-live"
output: html_document
date: "2025-02-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE)
library(tidyverse)
```

# Wednesday

## dataset

```{r}
drinks = tibble(
  Row = 1:4,
  Drink = c("Milk Tea", "Espresso", "Latte", "Espresso"),
  Cafe = c("Happy Tea", "Daily Grind", "Daily Grind", "Bev's Beverages"),
  Price = c(4, 2, 3, 2)
)

drinks
```

```{r}
discounts = tibble(
  Row = 1:3,
  Coupon = c("25%", "50%", "5%"),
  Cafe = c("Happy Tea", "Daily Grind", "The Roast")
)

discounts
```

## Mutating joins

```{r}
left_join(drinks, discounts, by = "Cafe")
```

```{r}
right_join(drinks, discounts, by = "Cafe")

right_join(discounts, drinks, by = "Cafe")
```


```{r}
full_join(drinks, discounts, by = "Cafe")
```
```{r}
inner_join(drinks, discounts, by = "Cafe")
```

```{r}
left_join(drinks, discounts, by  = "Cafe")
```
```{r}
left_join(drinks, discounts)
```

```{r}
discounts1 <- discounts %>% rename(Locations = Cafe) %>% select(-Row)

discounts1 %>% left_join(drinks, by = join_by(Locations == Cafe))
```

## filtering joins

```{r}
semi_join(drinks, discounts, by = "Cafe")
semi_join(discounts, drinks, by = "Cafe")
```

```{r}
inner_join(drinks, discounts, by = "Cafe")
```

```{r}
anti_join(drinks, discounts, by = "Cafe")
anti_join(discounts, drinks, by = "Cafe")
```

Exercise:

```{r}
band_instruments
```

```{r}
band_members
```


```{r}
left_join(band_instruments, band_members)
```

```{r}
right_join(band_instruments, band_members)
```

```{r}
anti_join(band_instruments, band_members)
```

# Friday

## Pivoting

```{r}
players = tibble(
  player = c("Erling Haaland", "Kevin De Bruyne"),
  goals = c(36, 7),
  assists = c(8, 16),
  games = c(35, 32)
)

players
```

- `pivot_longer()`

```{r}
pivot_longer(players, c(goals, assists, games))

players_long <- pivot_longer(players, goals:games, names_to = "Stats", values_to = "Score")

pivot_longer(players, -player)
```

```{r}
players1 <- players %>% mutate(title = c("player_of_match", "none"))
players1
```

```{r}
players1 %>%  pivot_longer(goals:title)

players1 %>% mutate(win = c(T, F)) %>% pivot_longer(c(goals:games, win))
```

- `pivot_wider()`

```{r}
players_long <- pivot_longer(players, goals:games, names_to = "Stats", values_to = "Score")

players_long %>% pivot_wider(names_from = Stats, values_from = Score)

pivot_longer(players, goals:games) %>% pivot_wider()
```

Exercise:

```{r}
table1
```

```{r}
table2
```

```{r}
# table1 -> table2

table1 %>% pivot_longer(c(cases, population), names_to = "type", values_to = "count")

table1 %>% pivot_longer(-c(country, year), names_to = "type", values_to = "count")
```

```{r}
# table2 -> table1

table2 %>% pivot_wider(names_from = type, values_from = count)
```
```{r}
table1 %>% pivot_longer(-country)
```

```{r}
mendota <- read_csv("../../data/lake-mendota-winters-2024.csv")
```

```{r}
ggplot(mendota, aes(duration)) +
  geom_histogram(
    color = "blue",
    fill = "skyblue"
  ) +
  geom_text(
    x = 79,
    y = 21,
    label = "this is the tallest bar ->",
    color = "red"
  )
```


# End of the midterm 1















