---
title: "week07_001-live"
output: html_document
date: "2025-03-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
source("../../scripts/ggprob.R")
```


```{r}
choose(400, 20) *( (1/2)^20) * ((1/2)^380)
```

```{r}
dbinom(20, 400, 0.5)
```



```{r}
dbinom(0:2, 4, 0.5)

# probability of getting atmost 2 heads

sum(dbinom(0:2, 4, 0.5))

pbinom(2, 4, 0.5)

qbinom(0.5, 4, 0.5)
pbinom(2, 4, 0.5)
```

```{r}
# probability of getting atleast 2 head in 4 coin flips

1 - pbinom(1,4,1/2)

pbinom(1, 4, 1/2, lower.tail = F)
```

```{r}
qbinom(0.5, 4, 1/2)
qbinom(0.6, 4, 1/2)

pbinom(1:3, 4, 0.5)

rbinom(100, 4, 1/2)
```
```{r}
gbinom(4,1/2)
```

# Normal distribution

```{r}
dnorm(12, 100, 25)
dnorm(100, 100, 25)
```


```{r}
pnorm(105,100, 25)
pnorm(104.99999, 100, 25)

pnorm(105, 100, 25, lower.tail = F)
1-pnorm(105, 100, 25)
```

```{r}
qnorm(0.5, 100, 25)
pnorm(100, 100, 25)

qnorm(0.4, 100, 25)
qnorm(0.6, 100, 25, lower.tail = F)
```


```{r}
rnorm(1000, 100, 25)
```

```{r}
x = 24

pnorm(24, 20, 5)
pnorm((24-20)/5, 0, 1)
```


```{r}

```





